<?php

namespace Database\Seeders;

use App\Models\Oficialidades\Institucion;
use Illuminate\Database\Seeder;

class InstitucionSeeder extends Seeder
{
    public function run(): void
    {

        $instituciones = [
            ["FISCALÍA GENERAL DE AGUASCALIENTES", "FGAGS"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE BAJA CALIFORNIA", "FGBC"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE BAJA CALIFORNIA SUR", "FGBCS"],
            ["FISCALÍA GENERAL DE CAMPECHE", "FGCAM"],
            ["FISCALÍA GENERAL DE COAHUILA", "FGCOA"],
            ["FISCALÍA GENERAL DE COLIMA", "FGCOL"],
            ["FISCALÍA GENERAL DE CHIAPAS", "FGCHS"],
            ["FISCALÍA GENERAL DE CHIHUAHUA", "FGCHI"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DE LA CIUDAD DE MÉXICO", "FGCDMX"],
            ["FISCALÍA GENERAL DE DURANGO", "FGDUR"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE GUANAJUATO", "FGGTO"],
            ["FISCALÍA GENERAL DE GUERRERO", "FGGRO"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE HIDALGO", "FGHGO"],
            ["FISCALÍA GENERAL DE JALISCO", "FGJAL"],
            ["FISCALÍA GENERAL DEL ESTADO DE MÉXICO", "FGMEX"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE MICHOACÁN", "FGMIC"],
            ["FISCALÍA GENERAL DE MORELOS", "FGMOR"],
            ["FISCALÍA GENERAL DE NAYARIT", "FGNAY"],
            ["FISCALÍA GENERAL DE NUEVO LEÓN", "FGNL"],
            ["FISCALÍA GENERAL DE OAXACA", "FGOAX"],
            ["FISCALÍA GENERAL DE PUEBLA", "FGPUE"],
            ["FISCALÍA GENERAL DE QUERÉTARO", "FGQRO"],
            ["FISCALÍA GENERAL DE QUINTANA ROO", "FGQROO"],
            ["FISCALÍA GENERAL DE SAN LUIS POTOSÍ", "FGSLP"],
            ["FISCALÍA GENERAL DE SINALOA", "FGSIN"],
            ["FISCALÍA GENERAL DE SONORA", "FGSON"],
            ["FISCALÍA GENERAL DE TABASCO", "FGTAB"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE TAMAULIPAS", "FGTAM"],
            ["PROCURADURÍA GENERAL DE JUSTICIA DEL ESTADO DE TLAXCALA", "FGTLA"],
            ["FISCALÍA GENERAL DE VERACRUZ", "FGE"],
            ["FISCALÍA GENERAL DE YUCATÁN", "FGYUC"],
            ["FISCALÍA GENERAL DE ZACATECAS", "FGZAC"],
            ["SE DESCONOCE", "SD"],
            ["FISCALÍA ESPECIAL PARA LOS DELITOS DE VIOLENCIA CONTRA LAS MUJERES Y TRATA DE PERSONAS", "FEVIMTRA"],
            ["SUBPROCURADURÍA DERECHOS HUMANOS, ATENCIÓN A VÍCTIMAS Y SERVICIOS A LA COMUNIDAD", "SDHAVSC"],
            ["SUBPROCURADURÍA ESPECIALIZADA EN INVESTIGACIÓN DE DELITOS FEDERALES", "SEIDF"],
            ["SUBPROCURADURÍA ESPECIALIZADA EN INVESTIGACIÓN DE DELINCUENCIA ORGANIZADA", "SEIDO"],
            ["SUBPROCURADURÍA JURÍDICA Y DE ASUNTOS INTERNACIONALES", "SJAI"],
            ["SUBPROCURADURÍA DE CONTROL REGIONAL, PROCEDIMIENTOS PENALES Y AMPARO", "SCRPPA"],
            ["APLICACIÓN WEB", "APP"],
            ["OTRA", "OTRA"],
            ["COMISIÓN NACIONAL DE BÚSQUEDA DE PERSONAS", "CNB"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE AGUASCALIENTES", "CLBAGS"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE BAJA CALIFORNIA", "CLBBC"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE BAJA CALIFORNIA SUR", "CLBBCS"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE CAMPECHE", "CLBCAM"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE COAHUILA", "CLBCOA"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE COLIMA", "CLBCOL"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE CHIAPAS", "CLBCHS"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE CHIHUAHUA", "CLBCHI"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DE LA CIUDAD DE MÉXICO", "CLBCDMX"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE DURANGO", "CLBDUR"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE GUANAJUATO", "CLBGTO"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE GUERRERO", "CLBGRO"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE HIDALGO", "CLBHGO"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE JALISCO", "CLBJAL"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE MÉXICO", "CLBMEX"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE MICHOACÁN", "CLBMIC"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE MORELOS", "CLBMOR"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE NAYARIT", "CLBNAY"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE NUEVO LEÓN", "CLBNL"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE OAXACA", "CLBOAX"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE PUEBLA", "CLBPUE"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE QUERÉTARO", "CLBQRO"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE QUINTANA ROO", "CLBQR"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE SAN LUIS POTOSÍ", "CLBSLP"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE SINALOA", "CLBSIN"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE SONORA", "CLBSON"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE TABASCO", "CLBTAB"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE TAMAULIPAS", "CLBTAM"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE TLAXCALA", "CLBTLA"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE VERACRUZ", "CLBVER"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE YUCATÁN", "CLBYUC"],
            ["COMISIÓN LOCAL DE BÚSQUEDA DE PERSONAS DEL ESTADO DE ZACATECAS", "CLBZAC"],
            ["SUBPROCURADURÍA DE DERECHOS HUMANOS, PREVENCIÓN DEL DELITO Y SERVICIOS A LA COMUNIDAD", "SDHPDSC"],
            ["FISCALÍA GENERAL DE LA REPÚBLICA", "FGR"],
            ["JUZGADO DE DISTRITO", "TBD"]
        ];

        foreach ($instituciones as $institucion) {
            Institucion::create([
                'nombre' => $institucion[0],
                'abreviatura' => $institucion[1]
            ]);
        }
    }
}
