<?php

namespace Database\Seeders;

use App\Models\MarcaVehiculo;
use Illuminate\Database\Seeder;

class MarcaVehiculoSeeder extends Seeder
{
    public function run(): void
    {
        $marcas = [
            'Acura',
            'Alfa Romeo',
            'Altamirano',
            'Arsata',
            'Audi',
            'Autocar',
            'Baic',
            'Bentley',
            'Bmw',
            'Cadillac',
            'Cage',
            'Cajoma',
            'Camarsa',
            'Carabela',
            'Carmex',
            'Case',
            'Caterpillar',
            'Caytrasa',
            'Cdmrsa',
            'Cese',
            'Chevrolet',
            'Chon',
            'Chrysler',
            'Corpus Christi',
            'Crumont',
            'Dab',
            'Datsun',
            'Dina',
            'Dodge',
            'Dorsey',
            'Ducati',
            'Famsa',
            'Faw',
            'Ferbus',
            'Ferrari',
            'Fiat',
            'Ford',
            'Fraightliner',
            'Fruehauf',
            'Garcia Diaz',
            'Garel',
            'General Motors',
            'Gmc',
            'Hardley Davison',
            'Hartford',
            'Herchee',
            'Honda',
            'Hummer',
            'Hyundai',
            'Igsa',
            'Indeterminado',
            'Indiam',
            'Infiniti',
            'Inmarsa',
            'Inresa',
            'Internacional',
            'Isuzu',
            'Jac',
            'Jaguar',
            'Jeep',
            'John Deere',
            'Kawasaki',
            'Kenworth',
            'Kia',
            'Krupp',
            'Land Rover',
            'Lincoln',
            'Lotus',
            'Lozano',
            'Lufkin',
            'Mack',
            'Majestic',
            'Marentes',
            'Mareqsa',
            'Masa',
            'Maserati',
            'Mata',
            'Mazda',
            'Mercedes Benz',
            'Mercury',
            'Mg',
            'Mg Rover',
            'Mini',
            'Mitsubishi',
            'Monterrey',
            'Motocicletas',
            'Murrel',
            'Nacasa',
            'Navistar',
            'Nissan',
            'Oisa',
            'Palfinger',
            'Peña Motors',
            'Peter Bilt',
            'Peugeot',
            'Piaggio',
            'Pines',
            'Plymouth',
            'Polar',
            'Pontiac',
            'Porsche',
            'Quinsa',
            'Rambler',
            'Remosa',
            'Renault',
            'Roccsa',
            'Rover',
            'Saab',
            'Sanyang',
            'Scania',
            'Seat',
            'Sgcu',
            'Sin Informacion',
            'Smart',
            'Subaru',
            'Sust. Motos (Cancelado)',
            'Suzuki',
            'Takt',
            'Taylor',
            'Texu',
            'Timpte',
            'Toyota',
            'Tractocamion',
            'Trailmobile',
            'Tramosa',
            'Triunfo',
            'Tunera',
            'Utility',
            'Vam',
            'Vespa',
            'Vespino',
            'Volkswagen',
            'Volvo',
            'Wabash',
            'White',
            'Yamaha',
            'Zanella'
        ];

        foreach ($marcas as $marca) {
            MarcaVehiculo::create(['nombre' => $marca]);
        }
    }
}
