<?php

namespace Database\Seeders;

use App\Models\Nacionalidad;
use App\Models\Personas\Persona;
use Illuminate\Database\Seeder;

class NacionalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nacionalidades = [
            "AFGANA",
            "ALBANESA",
            "ALEMANA",
            "ANDORRANA",
            "ANGOLENSE",
            "ANTIGUO",
            "ANTILLANA",
            "ARABE",
            "ARABE (EMIRATOS ARABES)",
            "ARGELINA",
            "ARGENTINA",
            "ARMENIO",
            "AUSTRALIANA",
            "AUSTRIACA",
            "AZERBAIANA",
            "BAHAMEÑA",
            "BAHREINÍ",
            "BANGLADESHÍ",
            "BELGA",
            "BELICEÑA",
            "BERMUDAS",
            "BIRMANA",
            "BOLIVIANA",
            "BOSNIO-HERZEGOVINO",
            "BRASILEÑA",
            "BRUNEIANA",
            "BULGARA",
            "BUTANESA",
            "CAMERUNESA",
            "CANADIENSE",
            "CHECA",
            "CHILENA",
            "CHINA",
            "CHIPRIOTA",
            "COLOMBIANA",
            "COREANA (DEL SUR)",
            "COREANA (REPUBLICA POPULAR)",
            "COSTA RICA",
            "CROATA",
            "CUBANA",
            "DADÁ",
            "DANESA",
            "DOMINICANA",
            "ECUATORIANA",
            "EGIPCIA",
            "ESPAÑOLA",
            "ESTADOUNIDENSE",
            "ESTONIA",
            "ETÍOPE",
            "FILIPINA",
            "FINLANDESA",
            "FRANCESA",
            "GABONESA",
            "GEORGIANA",
            "GRIEGA",
            "GROELANDESA",
            "GUATEMALTECA",
            "GUYANESA",
            "HAITIANA",
            "HINDÚ",
            "HOLANDESA",
            "HONDUREÑA",
            "HONG KONG",
            "HÚNGARA",
            "INDONESIA",
            "INGLESA",
            "IRANÍ",
            "IRAQUÍ",
            "IRLANDESA",
            "ISLANDESA",
            "ISRAELI",
            "ITALIANA",
            "JAMAICANA",
            "JAPONESA",
            "JORDANA",
            "KAMPUCHEANA",
            "KATARENSE",
            "KENYANA",
            "KIRGUISA",
            "KUWAITÍ",
            "LAOCIANA",
            "LIECHTENSTEINIANA",
            "LEONESA",
            "LIBANESA",
            "LITUANA",
            "LUXEMBURGESA",
            "MALAYA",
            "MALDIVIANA",
            "MALTESA",
            "MARROQUÍ",
            "MEXICANA",
            "MOLDAVA",
            "MONEGASCA",
            "MONGOLA",
            "MOZAMBIQUEÑA",
            "NEOZELANDESA",
            "SANEPALESA",
            "NICARAGUENSE",
            "NIGERIANA",
            "NORUEGA",
            "OMANÍ",
            "PANAMEÑA",
            "PAQUISTANÍ",
            "PARAGUAYA",
            "PERUANA",
            "POLACA",
            "POLINESIA",
            "PORTUGUESA",
            "PUERTORRIQUEÑA",
            "RUMANA",
            "RUSA",
            "SALVADOREÑA",
            "SANMARINENSE",
            "SIN ESPECIFICAR",
            "SINGAPURENSE",
            "SIRIA",
            "ESLOVACA",
            "ESLOVENA",
            "SRI LANKA",
            "SUDAFRICANA",
            "SUECA",
            "SUIZA",
            "SURINAMESA",
            "TAILANDESA",
            "TIBETANA",
            "TUNEZINA",
            "TURCA",
            "UCRANIANA",
            "URUGUAYA",
            "VENEZOLANA",
            "VIETNAMITA",
            "YEMENITA (REP. ARABE)",
            "YEMENITA (REP. DEMOC. POP)",
            "YUGOSLAVA",
            "SIN CONOCIMIENTO"
        ];

        foreach ($nacionalidades as $nacionalidad) {
            Nacionalidad::create([
                'nombre' => $nacionalidad,
            ]);
        }
    }
}
