<?php

namespace Database\Seeders;

use App\Models\Nacionalidad;
use App\Models\Personas\Persona;
use Illuminate\Database\Seeder;

class NacionalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nacionalidades = [
            'AFGANA',
            'ALBANESA',
            'ALEMANA',
            'AMERICANA',
            'ANDORRANA',
            'ANGOLESA',
            'ARABE',
            'ARGELIANA',
            'ARGENTINA',
            'AUSTRALIANA',
            'AUSTRIACA',
            'BAHAMEÑA',
            'BELGA',
            'BELICEÑA',
            'BHUTANESA',
            'BIRMANA',
            'BOLIVIANA',
            'BOTSWANESA',
            'BRASILEÑA',
            'BRITANICA',
            'BRITANICA',
            'BULGARA',
            'BURKINA FASO',
            'BURUNDESA',
            'CAMBOYANA',
            'CAMERUNESA',
            'CANADIENSE',
            'CENTRO AFRICANA',
            'CHADIANA',
            'CHECOSLOVACA',
            'CHILENA',
            'CHINA',
            'CHIPRIOTA',
            'COLOMBIANA',
            'COMORENSE',
            'CONGOLESA',
            'COSTARRICENSE',
            'CUBANA',
            'DANESA',
            'DE BAHREIN',
            'DE BARBADOS',
            'DE BENNIN',
            'DE CABO VERDE',
            'DE DJIBOUTI',
            'DE SANTO TOME',
            'DE SEYCHELLES',
            'DE ZIMBAWI',
            'DEL QATAR',
            'DEL SAHARA',
            'DOMINICA',
            'DOMINICANA',
            'EGIPCIA',
            'ESLOVACA',
            'ESLOVAQUIA',
            'ESLOVENIA',
            'ESPAÑOLA',
            'ESTADOUNIDENSE',
            'ESTONIA',
            'ETIOPE',
            'FIJIANA',
            'FILIPINA',
            'FINLANDESA',
            'FRANCESA',
            'GABONESA',
            'GAMBIANA',
            'GHANATA',
            'GRANADINA',
            'GRIEGA',
            'GUATEMALTECA',
            'GUINEA ECUATORIANA',
            'GUINEA',
            'GUINEA',
            'GUYANESA',
            'HAITIANA',
            'HINDU',
            'HOLANDESA',
            'HONDUREÑA',
            'HUNGARA',
            'INDONESA',
            'IRANI',
            'IRAQUI',
            'IRLANDESA',
            'ISLANDESA',
            'ISRAELI',
            'ITALIANA',
            'JAMAIQUINA',
            'JAPONESA',
            'JORDANA',
            'KENIANA',
            'KIRGUISTAN',
            'KUWAITI',
            'LAOSIANA',
            'LESOTHENSE',
            'LIBANESA',
            'LIBERIANA',
            'LIBIA',
            'LIECHTENSTENSE',
            'LITUANIA',
            'LUXEMBURGUESA',
            'MACEDONIA',
            'MALASIA',
            'MALAWIANA',
            'MALDIVA',
            'MALIENSE',
            'MALTESA',
            'MARFILEÑA',
            'MARROQUI',
            'MAURICIANA',
            'MAURITANA',
            'MEXICANA',
            'MICRONECIA',
            'MOLDOVIA, REPUBLICA DE',
            'MONEGASCA',
            'MONGOLESA',
            'MOZAMBIQUEÑA',
            'NAMIBIANA',
            'NAURUANA',
            'NEPALESA',
            'NICARAGUENSE',
            'NIGERIANA',
            'NIGERINA',
            'NORCOREANA',
            'NORUEGA',
            'NORVIETNAMITA',
            'OMANESA',
            'PAKISTANI',
            'PANAMEÑA',
            'PAPUENSE',
            'PARAGUAYA',
            'PERUANA',
            'PORTUGUESA',
            'PUERTORRIQUEÑA',
            'REINO UNIDO',
            'REINO UNIDO(BRIT. DEL EXT.)',
            'REINO UNIDO(C. BRIT. DEL EXT.)',
            'REINO UNIDO(DEPEN. TET. BRIT.)',
            'RUMANA',
            'RWANDESA',
            'SALOMONESA',
            'SALVADOREÑA',
            'SAMOANA',
            'SAN MARINENSE',
            'SANTA LUCIENSE',
            'SENEGALESA',
            'SIERRA LEONESA',
            'SINGAPORENSE',
            'SIRIA',
            'SOMALI',
            'SOVIETICA BIELORRUSA',
            'SOVIETICA UCRANIANA',
            'SUDAFRICANA',
            'SUDANESA',
            'SUDCOREANA',
            'SUECA',
            'SUIZA',
            'SURINAMENSE',
            'SWAZI',
            'TAILANDESA',
            'TAIWANESA',
            'TANZANIANA',
            'TOGOLESA',
            'TRINITARIA',
            'TUNECINA',
            'TURCA',
            'UGANDESA',
            'URUGUAYA',
            'VATICANA',
            'VENEZOLANA',
            'YEMENI',
            'YUGOSLAVA',
            'ZAIRANA',
            'ZAMBIANA', 
        ];

        foreach ($nacionalidades as $nacionalidad) {
            Nacionalidad::create([
                'nombre' => $nacionalidad,
            ]);
        }

        Persona::factory()
            ->hasAttached(Nacionalidad::inRandomOrder()->first())
            ->create();
    }
}
