<?php

namespace Database\Seeders;

use App\Models\Nacionalidad;
use App\Models\Personas\Persona;
use Illuminate\Database\Seeder;

class NacionalidadSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $nacionalidades = [
            "Namibiana",
            "Angolesa",
            "Argeliana",
            "De Bennin",
            "Botswanesa",
            "Burundesa",
            "De Cabo Verde",
            "Comorense",
            "Congolesa",
            "Marfileña",
            "Chadiana",
            "De Djibouti",
            "Egipcia",
            "Etiope",
            "Gabonesa",
            "Gambiana",
            "Ghanata",
            "Guinea",
            "Guinea Ecuatoriana",
            "Libia",
            "Keniana",
            "Lesothense",
            "Liberiana",
            "Malawiana",
            "Maliense",
            "Marroqui",
            "Mauriciana",
            "Mauritana",
            "Mozambiqueña",
            "Nigerina",
            "Nigeriana",
            "Centro Africana",
            "Camerunesa",
            "Tanzaniana",
            "Rwandesa",
            "Del Sahara",
            "De Santo Tome",
            "Senegalesa",
            "De Seychelles",
            "Sierra Leonesa",
            "Somali",
            "Sudaficana",
            "Sudanesa",
            "Swazi",
            "Togolesa",
            "Tunecina",
            "Ugandesa",
            "Zairana",
            "Zambiana",
            "De Zimbawi",
            "Argentina",
            "Bahameña",
            "De Barbados",
            "Beliceña",
            "Boliviana",
            "Brasileña",
            "Canadiense",
            "Colombiana",
            "Costarricense",
            "Cubana",
            "Chilena",
            "Dominica",
            "Salvadoreña",
            "Estadounidense",
            "Granadina",
            "Guatemalteca",
            "Británica",
            "Guyanesa",
            "Haitiana",
            "Hondureña",
            "Jamaicana",
            "Mexicana",
            "Nicaragüense",
            "Panameña",
            "Paraguaya",
            "Peruana",
            "Puertorriqueña",
            "Dominicana",
            "Santa Luciense",
            "Surinamense",
            "Trinitaria",
            "Uruguaya",
            "Venezolana",
            "Americana",
            "Afgana",
            "De Bahrein",
            "Bhutanesa",
            "Birmana",
            "Norcoreana",
            "Sudcoreana",
            "China",
            "Chipriota",
            "Arabe",
            "Filipina",
            "Hindu",
            "Indonesa",
            "Iraquí",
            "Iraní",
            "Israelí",
            "Japonesa",
            "Jordana",
            "Camboyana",
            "Kuwaití",
            "Libanesa",
            "Malasia",
            "Maldiva",
            "Mongolesa",
            "Nepalesa",
            "Omanesa",
            "Pakistaní",
            "Del Qatar",
            "Siria",
            "Laosiana",
            "Singapurense",
            "Tailandesa",
            "Taiwanesa",
            "Turca",
            "Norvietnamita",
            "Yemení",
            "Albanesa",
            "Alemana",
            "Andorrana",
            "Austríaca",
            "Belga",
            "Búlgara",
            "Checoslovaca",
            "Danesa",
            "Vaticana",
            "Española",
            "Finlandesa",
            "Francesa",
            "Griega",
            "Húngara",
            "Irlandesa",
            "Islandesa",
            "Italiana",
            "Liechtenstense",
            "Luxemburguesa",
            "Maltesa",
            "Monegasca",
            "Noruega",
            "Holandesa",
            "Portuguesa",
            "Británica",
            "Soviética Bielorrusa",
            "Soviética Ucraniana",
            "Rumana",
            "San Marinense",
            "Sueca",
            "Suiza",
            "Yugoslava",
            "Australiana",
            "Fijiana",
            "Salomonesa",
            "Nauruana",
            "Papuense",
            "Samoana",
            "Eslovaca",
            "Burkina Faso",
            "Estonia",
            "Micronesia",
            "Reino Unido (Depen. Tet. Brit.)",
            "Reino Unido (Brit. del Ext.)",
            "Reino Unido (C. Brit. del Ext.)",
            "Reino Unido",
            "Kirguistán",
            "Lituania",
            "Moldavia, República de",
            "Macedonia",
            "Eslovenia",
            "Eslovaquia",
            "Rusa"
        ];

        sort($nacionalidades);

        foreach ($nacionalidades as $nacionalidad) {
            Nacionalidad::create([
                'nombre' => $nacionalidad,
            ]);
        }

        Persona::factory()
            ->count(4)
            ->hasAttached(Nacionalidad::inRandomOrder()->first())
            ->create();
    }
}
