<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ParentescoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \App\Models\Parentesco::insert([
            ["parentesco" => "Abogada"],
            ["parentesco" => "Abogado"],
            ["parentesco" => "Abuela"], //Existe cierta ambieguedad en algunos campos 
            ["parentesco" => "Abuela materna"],
            ["parentesco" => "Abuela paterna"],
            ["parentesco" => "Abuelo"],
            ["parentesco" => "Abuelo materno"],
            ["parentesco" => "Abuelo paterno"],
            ["parentesco" => "Abuelo/a"],
            ["parentesco" => "Amiga/conocida"],
            ["parentesco" => "Amigo/conocido"],
            ["parentesco" => "Clero"],
            ["parentesco" => "Comadre"],
            ["parentesco" => "Compadre"],
            ["parentesco" => "Compañera/esposa"],
            ["parentesco" => "Compañero(a)/esposo(a)"],
            ["parentesco" => "Compañero/esposo"],
            ["parentesco" => "Concubina"],
            ["parentesco" => "Concubinario"],
            ["parentesco" => "Contacto de empleo"],
            ["parentesco" => "Conyuge"],
            ["parentesco" => "Cuñada"],
            ["parentesco" => "Cuñado"],
            ["parentesco" => "Cuñado(a)"],
            ["parentesco" => "Empleada"],
            ["parentesco" => "Empleado"],
            ["parentesco" => "Esposa"],
            ["parentesco" => "Esposo"],
            ["parentesco" => "Expareja"],
            ["parentesco" => "Gemela (idéntico/monocigoto)"],
            ["parentesco" => "Gemelo (idéntico/monocigoto)"],
            ["parentesco" => "Hermana"],
            ["parentesco" => "Hermano"],
            ["parentesco" => "Hermano(a)"],
            ["parentesco" => "Hija"],
            ["parentesco" => "Hija adoptiva"],
            ["parentesco" => "Hijastra"],
            ["parentesco" => "Hijastro"],
            ["parentesco" => "Hijastro(a)"],
            ["parentesco" => "Hijo"],
            ["parentesco" => "Hijo adoptivo"],
            ["parentesco" => "Hijo(a)"],
            ["parentesco" => "Hijo(a) adoptivo(a)"],
            ["parentesco" => "Jefe"],
            ["parentesco" => "Jefa"],
            ["parentesco" => "Madrastra"],
            ["parentesco" => "Madre"],
            ["parentesco" => "Madre adoptiva"],
            ["parentesco" => "Madrina"],
            ["parentesco" => "Medio hermana materna"],
            ["parentesco" => "Medio hermana paterna"],
            ["parentesco" => "Medio hermano materno"],
            ["parentesco" => "Medio hermano paterno"],
            ["parentesco" => "Medio hermano(a) materno(o)"],
            ["parentesco" => "Medio hermano(a) paterno(a)"],
            ["parentesco" => "Nieta"],
            ["parentesco" => "Nieta materna"],
            ["parentesco" => "Nieta paterna"],
            ["parentesco" => "Nieto"],
            ["parentesco" => "Nieto materno"],
            ["parentesco" => "Nieto paterno"],
            ["parentesco" => "Nieto(a)"],
            ["parentesco" => "Novia"],
            ["parentesco" => "Novio"],
            ["parentesco" => "Novio(a)"],
            ["parentesco" => "Nuera"],
            ["parentesco" => "ONG"],
            ["parentesco" => "Padrastro"],
            ["parentesco" => "Padre"],
            ["parentesco" => "Padre adoptivo"],
            ["parentesco" => "Padrino"],
            ["parentesco" => "Pareja extramatrimonial"],
            ["parentesco" => "Prima"],
            ["parentesco" => "Prima materna"],
            ["parentesco" => "Prima paterna"],
            ["parentesco" => "Primo(a)"],
            ["parentesco" => "Primo"],
            ["parentesco" => "Primo materno"],
            ["parentesco" => "Primo parteno"],
            ["parentesco" => "Sobrina"],
            ["parentesco" => "Sobrina materna"],
            ["parentesco" => "Sobrina paterna"],
            ["parentesco" => "Sobrino"],
            ["parentesco" => "Sobrino materno"],
            ["parentesco" => "Sobrino paterno"],
            ["parentesco" => "Sobrino(a)"],
            ["parentesco" => "Suegra"],
            ["parentesco" => "Suegro"],
            ["parentesco" => "Suegro(a)"],
            ["parentesco" => "Tía"],
            ["parentesco" => "Tía materna"],
            ["parentesco" => "Tía paterna"],
            ["parentesco" => "Tío"],
            ["parentesco" => "Tío materno"],
            ["parentesco" => "Tío paterno"],
            ["parentesco" => "Tío(a)"],
            ["parentesco" => "Tutor"],
            ["parentesco" => "Tutura"],
            ["parentesco" => "Vecina"],
            ["parentesco" => "Vecino"],
            ["parentesco" => "Yerno"],
            ["parentesco" => "Otro"],
            ["parentesco" => "No específica"]
        ]);
    }
}
