<?php

namespace Database\Seeders;

use App\Models\Personas\Parentesco;
use Illuminate\Database\Seeder;

class ParentescoSeeder extends Seeder
{
    public function run(): void
    {
        $parentescos = [
            'Abogada',
            'Abogado',
            'Abuela',
            'Abuela Materna',
            'Abuela Paterna',
            'Abuelo',
            'Abuelo Materno',
            'Abuelo Paterno',
            'Abuelo(a)',
            'Amiga/Conocida',
            'Amigo/Conocido',
            'Clero',
            'Comadre',
            'Compadre',
            'Compañera/Esposa',
            'Compañero(a)/Esposo(a)',
            'Compañero/Esposo',
            'Concubina',
            'Concubinario',
            'Contacto de Empleo',
            'Cónyuge',
            'Cuñada',
            'Cuñado',
            'Cuñado(a)',
            'Empleada',
            'Empleado',
            'Esposa',
            'Esposo',
            'Expareja',
            'Gemela(Identico/Monocigoto)',
            'Gemelo(Identico/Monocigoto)',
            'Hermana',
            'Hermano',
            'Hermano(a)',
            'Hija',
            'Hija Adoptiva',
            'Hijastra',
            'Hijastro',
            'Hijastro(a)',
            'Hijo',
            'Hijo Adoptivo',
            'Hijo(a)',
            'Hijo(a) Adoptivo(a)',
            'Jefa',
            'Jefe',
            'Madrastra',
            'Madre',
            'Madre Adoptiva',
            'Madrina',
            'Medio Hermana Materna',
            'Medio Hermana Paterna',
            'Medio Hermano Materno',
            'Medio Hermano Paterno',
            'Medio Hermano(a) Materno(a)',
            'Medio Hermano(a) Paterno(a)',
            'Nieta',
            'Nieta Materna',
            'Nieta Paterna',
            'Nieto',
            'Nieto Materno',
            'Nieto Paterno',
            'Nieto(a)',
            'Novia',
            'Novio',
            'Novio(a)',
            'Nuera',
            'ONG',
            'Padrastro',
            'Padre',
            'Padre Adoptivo',
            'Padrino',
            'Pareja Extramatrimonial',
            'Prima',
            'Prima Materna',
            'Prima Paterna',
            'Prima(a)',
            'Primo',
            'Primo Materno',
            'Primo Paterno',
            'Sobrina',
            'Sobrina Materna',
            'Sobrina Paterna',
            'Sobrino',
            'Sobrino Materno',
            'Sobrino Paterno',
            'Sobrino(a)',
            'Suegra',
            'Suegro',
            'Suegro(a)',
            'Tía',
            'Tía Materna',
            'Tía Paterna',
            'Tío',
            'Tío Materno',
            'Tío Paterno',
            'Tío(a)',
            'Tutor',
            'Tutora',
            'Vecina',
            'Vecino',
            'Yerno',
            'Otro',
            'No Especifica'
        ];

        foreach ($parentescos as $parentesco) {
            Parentesco::create([
                'nombre' => $parentesco,
            ]);
        }
    }
}
