// @no-log
POST http://api_cebv.test/api/token?email=test@example.com&password=password&token_name=desktop
Accept: application/json


> {%
    client.global.set("auth_token", response.body.data.plain_text_token);
%}
