// @no-log
GET http://api_cebv.test/api/reportes/1
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
    "reporte_uno_id": 3,
    "reporte_dos_id": 1,
    "tipo": "Directo",
    "parentesco_id": 5
}


