// @no-log
POST http://api_cebv.test/api/documentos-legales
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{

    "desaparecido_id" : 2,
    "tipo_documento" : "AmparoBuscador"
}

